name: window_manager_plus
description: This plugin allows Flutter desktop apps to create and manage multiple windows, such as resizing and repositioning, and communicate between them.
version: 1.0.5
homepage: https://github.com/pichillilorenzo/window_manager_plus
repository: https://github.com/pichillilorenzo/window_manager_plus
issue_tracker: https://github.com/pichillilorenzo/window_manager_plus/issues
funding:
  - https://www.paypal.com/paypalme/LorenzoPichilli
platforms:
  #linux:
  macos:
  windows:
topics:
  - window
  - window-resize
  - window-manager
  - multi-window
  - desktop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  screen_retriever: ^0.2.0

dev_dependencies:
  dependency_validator: ^4.1.1
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      #linux:
      #  pluginClass: WindowManagerPlusPlugin
      macos:
        pluginClass: WindowManagerPlusPlugin
      windows:
        pluginClass: WindowManagerPlusPlugin
